name: CybridApiIdpSwift
targets:
  CybridApiIdpSwift:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [CybridApiIdpSwift/APIClient]
    info:
      path: ./Info.plist
      version: 0.60.8
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
