name: CybridApiIdSwift
targets:
  CybridApiIdSwift:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [CybridApiIdSwift/APIClient]
    info:
      path: ./Info.plist
      version: 0.26.3
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
