//
// CustomerTokensAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc open class CustomerTokensAPI : NSObject {

    /**
     Create customer access token
     
     - parameter postCustomerToken: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    @discardableResult
    open class func createCustomerToken(postCustomerToken: PostCustomerToken, apiResponseQueue: DispatchQueue = CybridApiIdpSwiftAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<CustomerToken, ErrorResponse>) -> Void)) -> RequestTask {
        return createCustomerTokenWithRequestBuilder(postCustomerToken: postCustomerToken).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(.success(response.body))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Create customer access token
     - POST /api/customer_tokens
     - Creates a customer JWT access token.  Required scopes: **customers:write** and **customers:read**
     - BASIC:
       - type: http
       - name: BearerAuth
     - OAuth:
       - type: oauth2
       - name: oauth2
     - parameter postCustomerToken: (body)  
     - returns: RequestBuilder<CustomerToken> 
     */
    open class func createCustomerTokenWithRequestBuilder(postCustomerToken: PostCustomerToken) -> RequestBuilder<CustomerToken> {
        let localVariablePath = "/api/customer_tokens"
        let localVariableURLString = CybridApiIdpSwiftAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postCustomerToken)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CustomerToken>.Type = CybridApiIdpSwiftAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
