//
// AccessTokenIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccessTokenIdpModel: Codable, JSONEncodable, Hashable {

    /** Identifier of the access token. */
    public var id: Int
    /** Client ID of the application the token was issued to. */
    public var applicationClientId: String
    /** Guid of the organization, bank or customer the issuing application belongs to. */
    public var applicationGuid: String?
    /** Type of the resource owner: user, or application for customer tokens owned by a bank application. */
    public var resourceOwnerType: String?
    /** Guid of the user, or of the bank that owns the owning application. */
    public var resourceOwnerGuid: String?
    /** ISO8601 datetime the token was created at. */
    public var createdAt: Date
    /** Lifetime of the token in seconds. Null for tokens that do not expire. */
    public var expiresIn: Int?
    /** ISO8601 datetime the token was revoked at. Null for tokens that are not revoked. */
    public var revokedAt: Date?

    public init(id: Int, applicationClientId: String, applicationGuid: String?, resourceOwnerType: String?, resourceOwnerGuid: String?, createdAt: Date, expiresIn: Int?, revokedAt: Date?) {
        self.id = id
        self.applicationClientId = applicationClientId
        self.applicationGuid = applicationGuid
        self.resourceOwnerType = resourceOwnerType
        self.resourceOwnerGuid = resourceOwnerGuid
        self.createdAt = createdAt
        self.expiresIn = expiresIn
        self.revokedAt = revokedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case applicationClientId = "application_client_id"
        case applicationGuid = "application_guid"
        case resourceOwnerType = "resource_owner_type"
        case resourceOwnerGuid = "resource_owner_guid"
        case createdAt = "created_at"
        case expiresIn = "expires_in"
        case revokedAt = "revoked_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(applicationClientId, forKey: .applicationClientId)
        try container.encode(applicationGuid, forKey: .applicationGuid)
        try container.encode(resourceOwnerType, forKey: .resourceOwnerType)
        try container.encode(resourceOwnerGuid, forKey: .resourceOwnerGuid)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(expiresIn, forKey: .expiresIn)
        try container.encode(revokedAt, forKey: .revokedAt)
    }
}

