//
// ApplicationWithSecretAllOfIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc public class ApplicationWithSecretAllOfIdpModel: NSObject, Codable, JSONEncodable {

    /** The OAuth2 application's secret. */
    public var secret: String

    public init(secret: String) {
        self.secret = secret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case secret
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(secret, forKey: .secret)
    }
}

