//
// ApplicationWithSecretIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc public class ApplicationWithSecretIdpModel: NSObject, Codable, JSONEncodable {

    public enum ScopesIdpModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case organizationsRead = "organizations:read"
        case organizationsWrite = "organizations:write"
        case banksRead = "banks:read"
        case banksWrite = "banks:write"
        case banksExecute = "banks:execute"
        case customersRead = "customers:read"
        case accountsRead = "accounts:read"
        case quotesRead = "quotes:read"
        case tradesRead = "trades:read"
        case transfersRead = "transfers:read"
        case externalBankAccountsRead = "external_bank_accounts:read"
        case workflowsRead = "workflows:read"
        case depositAddressesRead = "deposit_addresses:read"
        case accountsExecute = "accounts:execute"
        case customersWrite = "customers:write"
        case customersExecute = "customers:execute"
        case pricesRead = "prices:read"
        case quotesExecute = "quotes:execute"
        case tradesExecute = "trades:execute"
        case transfersExecute = "transfers:execute"
        case rewardsExecute = "rewards:execute"
        case rewardsRead = "rewards:read"
        case externalBankAccountsWrite = "external_bank_accounts:write"
        case externalBankAccountsExecute = "external_bank_accounts:execute"
        case workflowsExecute = "workflows:execute"
        case depositAddressesExecute = "deposit_addresses:execute"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Name provided for the OAuth2 application. */
    public var name: String
    /** The OAuth2 application's client ID. */
    public var clientId: String
    /** List of the scopes granted to the OAuth2 application. */
    public var scopes: [ScopesIdpModel]
    /** ISO8601 datetime the application was created at. */
    public var createdAt: Date
    /** The OAuth2 application's secret. */
    public var secret: String

    public init(name: String, clientId: String, scopes: [ScopesIdpModel], createdAt: Date, secret: String) {
        self.name = name
        self.clientId = clientId
        self.scopes = scopes
        self.createdAt = createdAt
        self.secret = secret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case clientId = "client_id"
        case scopes
        case createdAt = "created_at"
        case secret
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(scopes, forKey: .scopes)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(secret, forKey: .secret)
    }
}

