//
// AuthorizationIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthorizationIdpModel: Codable, JSONEncodable, Hashable {

    public enum ResourceTypeIdpModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case organization = "organization"
        case customer = "customer"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Identifier of the user authorization. */
    public var id: Int
    /** Guid of the user. */
    public var userGuid: String
    /** Type of the resource the authorization is on. */
    public var resourceType: ResourceTypeIdpModel
    /** Guid of the resource the authorization is on. */
    public var resourceGuid: String
    /** Portal the authorization routes to. Null for authorizations that have no portal. */
    public var portal: String?
    /** The list of scopes that the user is allowed to request. */
    public var allowedScopes: [String]
    /** ISO8601 datetime the authorization was disabled at. Null for enabled authorizations. */
    public var disabledAt: Date?
    /** ISO8601 datetime the record was created at. */
    public var createdAt: Date
    /** ISO8601 datetime the record was last updated at. */
    public var updatedAt: Date?

    public init(id: Int, userGuid: String, resourceType: ResourceTypeIdpModel, resourceGuid: String, portal: String?, allowedScopes: [String], disabledAt: Date?, createdAt: Date, updatedAt: Date? = nil) {
        self.id = id
        self.userGuid = userGuid
        self.resourceType = resourceType
        self.resourceGuid = resourceGuid
        self.portal = portal
        self.allowedScopes = allowedScopes
        self.disabledAt = disabledAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userGuid = "user_guid"
        case resourceType = "resource_type"
        case resourceGuid = "resource_guid"
        case portal
        case allowedScopes = "allowed_scopes"
        case disabledAt = "disabled_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userGuid, forKey: .userGuid)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encode(resourceGuid, forKey: .resourceGuid)
        try container.encode(portal, forKey: .portal)
        try container.encode(allowedScopes, forKey: .allowedScopes)
        try container.encode(disabledAt, forKey: .disabledAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

