//
// CustomerTokenIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc public class CustomerTokenIdpModel: NSObject, Codable, JSONEncodable {

    /** The JWT access token for the customer. */
    public var accessToken: String?

    public init(accessToken: String? = nil) {
        self.accessToken = accessToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accessToken, forKey: .accessToken)
    }
}

