//
// GroupAuthorizationIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GroupAuthorizationIdpModel: Codable, JSONEncodable, Hashable {

    /** The group authorization's guid. */
    public var guid: String
    /** Guid of the group. */
    public var groupGuid: String
    /** Guid of the organization linked to the group. */
    public var resourceGuid: String
    /** Type of the linked resource. */
    public var resourceType: String
    /** Scopes the group holds over the organization. */
    public var allowedScopes: [String]
    /** ISO8601 datetime the record was created at. */
    public var createdAt: Date
    /** ISO8601 datetime the record was last updated at. */
    public var updatedAt: Date?

    public init(guid: String, groupGuid: String, resourceGuid: String, resourceType: String, allowedScopes: [String], createdAt: Date, updatedAt: Date? = nil) {
        self.guid = guid
        self.groupGuid = groupGuid
        self.resourceGuid = resourceGuid
        self.resourceType = resourceType
        self.allowedScopes = allowedScopes
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
        case groupGuid = "group_guid"
        case resourceGuid = "resource_guid"
        case resourceType = "resource_type"
        case allowedScopes = "allowed_scopes"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(guid, forKey: .guid)
        try container.encode(groupGuid, forKey: .groupGuid)
        try container.encode(resourceGuid, forKey: .resourceGuid)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encode(allowedScopes, forKey: .allowedScopes)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

