//
// GroupIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GroupIdpModel: Codable, JSONEncodable, Hashable {

    /** The group's guid. */
    public var guid: String
    /** Name provided for the group. */
    public var name: String
    /** Type of the group. */
    public var type: String
    /** Guids of the users who are members of the group. */
    public var memberGuids: [String]
    /** ISO8601 datetime the record was created at. */
    public var createdAt: Date
    /** ISO8601 datetime the record was last updated at. */
    public var updatedAt: Date?

    public init(guid: String, name: String, type: String, memberGuids: [String], createdAt: Date, updatedAt: Date? = nil) {
        self.guid = guid
        self.name = name
        self.type = type
        self.memberGuids = memberGuids
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case guid
        case name
        case type
        case memberGuids = "member_guids"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(guid, forKey: .guid)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encode(memberGuids, forKey: .memberGuids)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

