//
// PatchApplicationIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for application update. */
public struct PatchApplicationIdpModel: Codable, JSONEncodable, Hashable {

    /** Name for the application. */
    public var name: String?
    /** List of public IPv4 addresses or CIDR ranges to allowlist for API access. Provide [] to clear the allowlist; omit to leave unchanged. */
    public var ipAllowlist: [String]?

    public init(name: String? = nil, ipAllowlist: [String]? = nil) {
        self.name = name
        self.ipAllowlist = ipAllowlist
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case ipAllowlist = "ip_allowlist"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(ipAllowlist, forKey: .ipAllowlist)
    }
}

