//
// PostBankApplicationIdpModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc public class PostBankApplicationIdpModel: NSObject, Codable, JSONEncodable {

    /** Name for the bank application. */
    public var name: String
    /** Bank guid the application is associated to. */
    public var bankGuid: String?

    public init(name: String, bankGuid: String? = nil) {
        self.name = name
        self.bankGuid = bankGuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case bankGuid = "bank_guid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(bankGuid, forKey: .bankGuid)
    }
}

